$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: amlv2-p-data-engineering
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
conda_file: data-engineering-conda.yml